first commit
KseniaKondrateva/sprint7 pull request #1
Opened 2024-06-25 12:57 UTC by KseniaKondrateva

2024-06-25 13:58 UTC, just-musha requested changes
Привет! Нужно добавить недостающие проверки. Остальное не критично, поправь если есть желание.

2024-06-25 13:58 UTC, just-musha commented on .DS_Store
Этот служебный файл, не нужен в репозитории

2024-06-25 13:58 UTC, just-musha commented on main_test.go
> +}
Между тестовыми функциям нужны пустые строки

2024-06-25 13:58 UTC, just-musha commented on main_test.go
> +
Лишняя пустая строка (в и других тестах тоже)

2024-06-25 13:58 UTC, just-musha commented on main_test.go
> +	assert.Equal(t, http.StatusOK, responseRecorder.Code, "expected status code: %d, got %d", http.StatusOK, responseRecorder.Code)
А можно обойтись стандартным выводом assert ?

Я бы убрала эту часть `"expected status code: %d, got %d", http.StatusOK, responseRecorder.Code)` тк она по сути дублирует стандартное сообщение которое и так будет. Чтобы не дублировать параметры

2024-06-25 13:58 UTC, just-musha commented on main_test.go
> +	assert.Len(t, list, totalCount, "expected cafe count: %d, got %d", totalCount, len(list))
Тут можно ещё содержимое тела ответа проверить, не только количество

2024-06-25 13:58 UTC, just-musha commented on main_test.go
> +	assert.NotEmpty(t, body, "expected a non-empty response body")
Тут тоже надо ещё тело ответа проверить. NotEmpty - проверка ок, но само содержание тож надо сравнить

2024-06-27 08:53 UTC, KseniaKondrateva commented
добавила недостающие проверки, удалила ненужный файл

2024-06-27 08:59 UTC, KseniaKondrateva commented
добавила недостающие тесты, удалила ненужный файл

2024-06-27 09:04 UTC, KseniaKondrateva commented
добавила недостающие проверки, удалила ненужный файл

2024-06-27 12:25 UTC, just-musha approved these changes
Отлично! Принято! Успехов дальше на курсе.

2024-07-09 19:04 UTC, closed without merging